import { useEffect, useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Trash2, AlertTriangle, Save, RotateCcw } from "lucide-react";
import { toast } from "sonner";
import WeeklyTimetable from "../components/course/WeeklyTimetable";
import { useCourseStore } from "../store/courseStore";
import { useUserStore } from "../store/userStore";
import { getConflicts, getTotalCredits } from "../utils/courseRules";
import { Link } from "react-router-dom";

export default function TimetablePage(){
 const selected=useCourseStore(s=>s.selected), removeSelected=useCourseStore(s=>s.removeSelected), clearSelected=useCourseStore(s=>s.clearSelected);
 const user=useUserStore(s=>s.user); const [savedAt,setSavedAt]=useState<string|null>(null);
 const totalCredits=getTotalCredits(selected); const conflicts=useMemo(()=>getConflicts(selected),[selected]);
 useEffect(()=>{const raw=localStorage.getItem("timetable-snapshot"); if(raw){try{const snapshot=JSON.parse(raw);setSavedAt(snapshot.savedAt??null);}catch{localStorage.removeItem("timetable-snapshot");}}},[]);
 const save=()=>{const now=new Date().toISOString(); localStorage.setItem("timetable-snapshot",JSON.stringify({savedAt:now,courses:selected}));setSavedAt(now);toast.success("현재 시간표를 저장했습니다.");};
 const restore=()=>{const raw=localStorage.getItem("timetable-snapshot"); if(!raw){toast.info("저장된 시간표가 없습니다.");return;} try{const snapshot=JSON.parse(raw); if(!Array.isArray(snapshot.courses)){throw new Error();} useCourseStore.setState({selected:snapshot.courses}); setSavedAt(snapshot.savedAt??null); toast.success("저장된 시간표를 불러왔습니다.");}catch{toast.error("저장된 시간표를 불러오지 못했습니다.");}};
 return <main className="mx-auto w-full max-w-[1500px] px-4 py-6 font-['Pretendard',sans-serif] text-[#20212b] min-[1101px]:px-7">
  <div className="mb-4 grid gap-3 sm:grid-cols-3"><Stat label="총 신청 학점" value={`${totalCredits}/${user?.maxCredits??18}`} sub={totalCredits>(user?.maxCredits??18)?"학점 초과":"신청 한도 내"} danger={totalCredits>(user?.maxCredits??18)}/><Stat label="선택 강좌" value={`${selected.length}개`} sub="현재 시간표 기준"/><Stat label="시간 충돌" value={`${conflicts.length}건`} sub={conflicts.length?"아래 충돌 목록을 확인하세요":"충돌 없음"} danger={!!conflicts.length}/></div>
  <div className="grid gap-4 min-[1101px]:grid-cols-[minmax(0,1.4fr)_minmax(340px,0.75fr)]"><div><WeeklyTimetable selected={selected}/><div className="mt-4 flex flex-wrap items-center justify-between gap-2"><div className="text-[8px] text-[#9699a7]">{savedAt?`마지막 저장 ${new Date(savedAt).toLocaleString("ko-KR",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}`:"아직 저장하지 않았습니다."}</div><div className="flex flex-wrap justify-end gap-2"><button onClick={restore} className="flex items-center gap-1.5 rounded-lg border border-[#dedfe5] px-3 py-2.5 text-[9px] font-semibold text-[#777985]"><RotateCcw size={12}/> 저장 불러오기</button><button onClick={save} disabled={!selected.length} className="flex items-center gap-1.5 rounded-lg bg-[#7658e9] px-4 py-2.5 text-[9px] font-bold text-white disabled:bg-[#d8d6e3]"><Save size={12}/> 현재 시간표 저장</button><button onClick={()=>{if(selected.length&&window.confirm("선택한 강좌를 모두 삭제할까요?"))clearSelected();}} className="rounded-lg border border-[#dedfe5] px-4 py-2.5 text-[9px] font-semibold text-[#777985]">전체 비우기</button></div></div></div>
   <section className="rounded-xl border border-[#e3e4e9] bg-white shadow-[0_3px_14px_rgba(26,28,44,0.035)]"><div className="border-b border-[#ececf0] px-5 py-4"><div className="flex items-center gap-2"><CalendarDays size={15} className="text-[#7658e9]"/><div><h1 className="text-sm font-bold">나의 시간표</h1><p className="mt-1 text-[9px] text-[#9699a7]">강의 검색에서 선택한 과목이 자동 반영됩니다.</p></div></div></div>
    {selected.length===0?<div className="px-5 py-14 text-center"><p className="text-[10px] text-[#9699a7]">아직 선택한 강좌가 없습니다.</p><Link to="/courses" className="mt-3 inline-block rounded-lg bg-[#7658e9] px-4 py-2 text-[9px] font-bold text-white">강의 검색하기</Link></div>:<div>{selected.map(course=><div key={course.id} className="border-b border-[#f0f0f3] px-5 py-4"><div className="flex items-start justify-between gap-3"><div><b className="text-[10px]">{course.title}</b><p className="mt-1 text-[8px] text-[#9699a7]">{course.courseCode} · {course.professorName} · {course.credit}학점</p></div><button onClick={()=>{if(window.confirm(`'${course.title}' 강의를 시간표에서 삭제할까요?`)) removeSelected(course.id);}} className="rounded-md p-1.5 text-[#a0a2ad] hover:bg-[#fff2f3] hover:text-[#df6471]" aria-label="강의 삭제"><Trash2 size={13}/></button></div><div className="mt-2 text-[8px] text-[#777985]">{course.isOnline?"온라인 강의":course.schedules.map(s=>`${s.dayOfWeek} ${s.startPeriod}~${s.endPeriod}교시 · ${s.classroom}`).join(" / ")}</div></div>)}</div>}
    <div className="border-t border-[#f0f0f3] bg-[#fafafd] px-5 py-4">{conflicts.length?<><p className="flex items-center gap-1.5 text-[9px] font-semibold text-[#d95d6b]"><AlertTriangle size={12}/> 시간 충돌 {conflicts.length}건이 있습니다.</p><div className="mt-3 space-y-2">{conflicts.map(({first,second,detail})=><div key={`${first.id}-${second.id}`} className="rounded-lg border border-[#f4d7db] bg-[#fff8f9] px-3 py-2 text-[8px] text-[#8d5961]"><b>{first.title}</b> ↔ <b>{second.title}</b><span className="ml-1">· {detail.day}요일 {detail.firstTime}</span></div>)}</div></>:<p className="flex items-center gap-1.5 text-[9px] font-semibold text-[#3b9279]"><CheckCircle2 size={12}/> 현재 시간표에 시간 충돌이 없습니다.</p>}<p className="mt-2 text-[8px] text-[#a0a3ae]">백엔드 연결 후 실제 수강신청 가능 여부를 함께 검증할 수 있습니다.</p></div>
   </section></div>
 </main>;
}
function Stat({label,value,sub,danger=false}:{label:string;value:string;sub:string;danger?:boolean}){return <div className="rounded-xl border border-[#e3e4e9] bg-white px-5 py-4 shadow-[0_3px_14px_rgba(26,28,44,0.025)]"><p className="text-[8px] text-[#9699a7]">{label}</p><p className={`mt-1 text-lg font-extrabold ${danger?"text-[#df6471]":"text-[#30313b]"}`}>{value}</p><p className={`mt-1 text-[8px] ${danger?"text-[#df6471]":"text-[#a0a3ae]"}`}>{sub}</p></div>}
